'use client';

import { useEffect, useState } from 'react';
import { CheckCircle2, EyeOff, RefreshCw, ShieldCheck } from 'lucide-react';
import type { DesignerPortfolio } from '@design-review/shared';
import { fetchWithAuth } from '@/lib/auth';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { AdminPagination } from '@/components/admin/admin-pagination';
import { toast } from 'sonner';

type ModerationItem = DesignerPortfolio & { designerName: string; designerAvatarUrl?: string };
const filters = [{ value: 'all', label: '全部作品' }, { value: 'draft', label: '待审核' }, { value: 'published', label: '已公开' }, { value: 'hidden', label: '已下架' }];

export default function DesignerModerationPage() {
  const [items, setItems] = useState<ModerationItem[]>([]); const [status, setStatus] = useState('all'); const [loading, setLoading] = useState(true); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const pageSize = 20;
  const load = async (nextPage = page) => { setLoading(true); try { const response = await fetchWithAuth(`/admin/designer-portfolios?status=${status}&page=${nextPage}&pageSize=${pageSize}`); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || '审核数据加载失败'); setItems(result.data || []); setTotal(result.total || 0); } catch (error: any) { toast.error(error.message || '审核数据加载失败'); } finally { setLoading(false); } };
  useEffect(() => { setPage(1); void load(1); }, [status]);
  const changePage = (nextPage: number) => { setPage(nextPage); void load(nextPage); };
  const update = async (item: ModerationItem, nextStatus: 'published' | 'hidden') => { const response = await fetchWithAuth(`/admin/designer-portfolios/${item.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: nextStatus }) }); const result = await response.json(); if (!response.ok || !result.success) return toast.error(result.message || '操作失败'); setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, status: nextStatus } : entry)); toast.success(result.message); };
  return <section className="mx-auto max-w-7xl space-y-5 p-8"><div className="flex flex-col gap-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold role-primary-text">内容治理</p><h1 className="mt-1 text-2xl font-bold text-slate-900">设计师主页与作品审核</h1><p className="mt-2 text-xs text-slate-500">审核公开作品，只有通过审核的作品和主页才会出现在品牌方推荐中。</p></div><Button variant="outline" onClick={() => void load()} disabled={loading} className="h-9 rounded-xl text-xs"><RefreshCw className={`mr-1.5 h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`} />刷新列表</Button></div><Card><CardHeader className="space-y-4"><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-4 w-4 role-primary-text" />作品审核列表<Badge variant="outline" className="ml-auto text-[10px]">共 {total} 项</Badge></CardTitle><div className="flex flex-wrap gap-1 rounded-xl bg-slate-100 p-1">{filters.map((item) => <button key={item.value} type="button" onClick={() => setStatus(item.value)} className={`rounded-lg px-3 py-1.5 text-xs transition ${status === item.value ? 'bg-white font-semibold role-primary-text shadow-sm' : 'text-slate-500 hover:text-slate-800'}`}>{item.label}</button>)}</div></CardHeader><CardContent className="p-0">{loading ? <div className="p-10 text-center text-xs text-slate-400">正在加载…</div> : items.length === 0 ? <div className="p-10 text-center text-xs text-slate-400">暂无符合条件的作品</div> : <><div className="grid gap-4 px-6 pb-6 sm:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="relative aspect-[4/3] bg-slate-100"><img src={item.coverUrl} alt={item.title} className="h-full w-full object-cover" /><Badge className={`absolute left-2 top-2 text-[10px] ${item.status === 'published' ? 'bg-emerald-500 text-white' : item.status === 'hidden' ? 'bg-slate-700 text-white' : 'bg-amber-500 text-white'}`}>{item.status === 'published' ? '已公开' : item.status === 'hidden' ? '已下架' : '待处理'}</Badge></div><div className="space-y-3 p-4"><div><h2 className="text-sm font-bold text-slate-800">{item.title}</h2><p className="mt-1 text-[11px] text-slate-400">设计师：{item.designerName} · {item.imageUrls.length} 张图片</p></div><div className="flex gap-2">{item.status !== 'published' && <Button type="button" onClick={() => void update(item, 'published')} className="role-primary-gradient h-8 flex-1 rounded-xl text-xs text-white"><CheckCircle2 className="mr-1 h-3.5 w-3.5" />通过公开</Button>}{item.status !== 'hidden' && <Button type="button" variant="outline" onClick={() => void update(item, 'hidden')} className="h-8 rounded-xl text-xs text-slate-600"><EyeOff className="mr-1 h-3.5 w-3.5" />下架</Button>}</div></div></article>)}</div><AdminPagination page={page} pageSize={pageSize} total={total} onPageChange={changePage} /></>}</CardContent></Card></section>;
}
