'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Area, AreaChart, Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowRight, CalendarClock, CheckCircle2, ClipboardCheck, FolderKanban, Gauge, LayoutDashboard, RefreshCw, Settings2, ShieldAlert, Sparkles, WalletCards } from 'lucide-react';
import type { DesignOrder, OrderDispute, ReviewRule } from '@design-review/shared';
import { fetchWithAuth } from '@/lib/auth';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { OrderModeDropdownButton } from '@/components/order-mode-dropdown';

const statusMap: Record<string, { label: string; className: string }> = {
  pending_deposit: { label: '待支付定金', className: 'bg-orange-50 text-orange-700 ring-1 ring-orange-100' }, pending_service_review: { label: '待客服审核', className: 'bg-amber-50 text-amber-700 ring-1 ring-amber-100' }, published: { label: '接单中', className: 'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-100' }, claimed: { label: '已接单', className: 'bg-sky-50 text-sky-700 ring-1 ring-sky-100' }, in_progress: { label: '制作中', className: 'bg-violet-50 text-violet-700 ring-1 ring-violet-100' }, submitted: { label: '待作品审核', className: 'bg-indigo-50 text-indigo-700 ring-1 ring-indigo-100' }, completed: { label: '已完成', className: 'bg-slate-100 text-slate-600 ring-1 ring-slate-200' }, rejected: { label: '已驳回', className: 'bg-rose-50 text-rose-700 ring-1 ring-rose-100' }, cancelled: { label: '已关闭', className: 'bg-slate-100 text-slate-600 ring-1 ring-slate-200' },
};
const chartColors = ['#4f46e5', '#0ea5e9', '#f59e0b', '#10b981'];
const formatDate = (value?: string) => value ? new Date(value).toLocaleDateString('zh-CN', { month: 'numeric', day: 'numeric' }) : '-';
const formatMoney = (value: number) => `¥${value.toLocaleString('zh-CN', { maximumFractionDigits: 0 })}`;
const orderStatus = (order: DesignOrder) => order.status === 'cancelled' && order.publicationStatus !== 'rejected' ? 'cancelled' : order.publicationStatus || order.status;

export default function AdvertiserDashboardPage() {
  const [orders, setOrders] = useState<DesignOrder[]>([]);
  const [rules, setRules] = useState<ReviewRule[]>([]);
  const [disputes, setDisputes] = useState<OrderDispute[]>([]);
  const [loading, setLoading] = useState(true);

  const loadDashboard = async () => {
    setLoading(true);
    try {
      const [ordersResponse, rulesResponse, disputesResponse] = await Promise.all([fetchWithAuth('/design-orders/mine'), fetchWithAuth('/review-rules/mine'), fetchWithAuth('/disputes')]);
      const [ordersResult, rulesResult, disputesResult] = await Promise.all([ordersResponse.json(), rulesResponse.json(), disputesResponse.json()]);
      if (!ordersResponse.ok || !ordersResult.success) throw new Error(ordersResult.message || '加载订单失败');
      if (!rulesResponse.ok || !rulesResult.success) throw new Error(rulesResult.message || '加载审核流失败');
      if (!disputesResponse.ok || !disputesResult.success) throw new Error(disputesResult.message || '加载纠纷失败');
      setOrders(ordersResult.data || []); setRules(rulesResult.data || []); setDisputes(disputesResult.data || []);
    } catch (error: any) { toast.error(error.message || '加载工作台失败'); } finally { setLoading(false); }
  };
  useEffect(() => { loadDashboard(); }, []);

  const metrics = useMemo(() => {
    const pending = orders.filter((order) => ['pending_deposit', 'pending_service_review', 'submitted'].includes(orderStatus(order))).length;
    const active = orders.filter((order) => ['published', 'claimed', 'in_progress'].includes(orderStatus(order))).length;
    const completed = orders.filter((order) => orderStatus(order) === 'completed').length;
    return { total: orders.length, pending, active, completed, totalBudget: orders.reduce((sum, order) => sum + Number(order.budget || 0), 0) };
  }, [orders]);
  const recentOrders = useMemo(() => [...orders].sort((a, b) => new Date(b.updatedAt || b.createdAt).getTime() - new Date(a.updatedAt || a.createdAt).getTime()).slice(0, 5), [orders]);
  const openDisputes = disputes.filter((item) => item.status !== 'resolved').length;
  const activeRules = rules.filter((item) => item.isActive).length;
  const pendingServiceReview = orders.filter((order) => orderStatus(order) === 'pending_service_review').length;
  const pendingWorkReview = orders.filter((order) => orderStatus(order) === 'submitted').length;
  const publishTrend = useMemo(() => Array.from({ length: 7 }, (_, offset) => {
    const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - 6 + offset);
    const next = new Date(date); next.setDate(next.getDate() + 1);
    return { label: `${date.getMonth() + 1}/${date.getDate()}`, orders: orders.filter((order) => { const createdAt = new Date(order.createdAt); return createdAt >= date && createdAt < next; }).length };
  }), [orders]);
  const statusData = useMemo(() => [{ name: '进行中', value: metrics.active }, { name: '待处理', value: metrics.pending }, { name: '已完成', value: metrics.completed }, { name: '其他', value: Math.max(0, metrics.total - metrics.active - metrics.pending - metrics.completed) }].filter((item) => item.value > 0), [metrics]);
  const categoryBudget = useMemo(() => Object.entries(orders.reduce<Record<string, number>>((result, order) => { const category = order.category || '未分类'; result[category] = (result[category] || 0) + Number(order.budget || 0); return result; }, {})).map(([name, budget]) => ({ name, budget })).sort((a, b) => b.budget - a.budget).slice(0, 4), [orders]);
  const todoItems = [{ label: '订单待审核', value: pendingServiceReview, href: '/advertiser/orders', icon: ClipboardCheck, className: 'from-amber-400 to-orange-500', ring: 'bg-amber-50 text-amber-700' }, { label: '作品待验收', value: pendingWorkReview, href: '/advertiser/orders', icon: CheckCircle2, className: 'from-indigo-500 to-violet-600', ring: 'bg-indigo-50 text-indigo-700' }, { label: '纠纷处理中', value: openDisputes, href: '/advertiser/disputes', icon: ShieldAlert, className: 'from-rose-400 to-pink-600', ring: 'bg-rose-50 text-rose-700' }];

  return <section className="mx-auto max-w-7xl space-y-6 pb-8">
    <div className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-indigo-700 via-violet-600 to-sky-500 px-6 py-7 text-white shadow-xl shadow-indigo-200 sm:px-8 lg:px-10">
      <div className="absolute -right-16 -top-16 h-56 w-56 rounded-full bg-cyan-300/30 blur-2xl" /><div className="absolute bottom-0 right-1/4 h-36 w-36 rounded-full bg-fuchsia-400/25 blur-2xl" />
      <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold text-indigo-100"><span className="flex h-6 w-6 items-center justify-center rounded-lg bg-white/15"><Sparkles className="h-3.5 w-3.5" /></span>创赢 · 品牌方运营中心</div><h1 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">让每一次视觉需求，都清晰可控。</h1><p className="mt-3 max-w-xl text-sm leading-6 text-indigo-100">汇总订单进度、预算使用与审核待办，快速推进下一步协作。</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={loadDashboard} disabled={loading} className="h-10 rounded-xl border-0 !bg-white !bg-none px-4 text-xs font-semibold !text-[var(--role-primary)] shadow-sm hover:!bg-slate-50 hover:!text-[var(--role-primary-dark)]"><RefreshCw className={`mr-1.5 h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`} />刷新数据</Button><Link href="/advertiser/review-flows"><Button variant="outline" className="h-10 rounded-xl border-0 !bg-white !bg-none px-4 text-xs font-semibold !text-[var(--role-primary)] shadow-sm hover:!bg-slate-50 hover:!text-[var(--role-primary-dark)]"><Settings2 className="mr-1.5 h-3.5 w-3.5" />审核流</Button></Link><OrderModeDropdownButton label="发布订单" className="inline-flex h-10 items-center rounded-xl !bg-white !bg-none px-4 text-xs font-semibold !text-[var(--role-primary)] shadow-sm hover:!bg-slate-50 hover:!text-[var(--role-primary-dark)]" /></div></div>
    </div>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: '全部订单', value: metrics.total, note: '订单资产总量', icon: FolderKanban, className: 'from-sky-500 to-cyan-500', soft: 'bg-sky-50 text-sky-600' }, { label: '待处理', value: metrics.pending, note: '需要品牌方操作', icon: CalendarClock, className: 'from-amber-400 to-orange-500', soft: 'bg-amber-50 text-amber-600' }, { label: '进行中', value: metrics.active, note: '设计协作推进中', icon: Gauge, className: 'from-violet-500 to-indigo-600', soft: 'bg-violet-50 text-violet-600' }, { label: '已完成', value: metrics.completed, note: '已完成验收交付', icon: CheckCircle2, className: 'from-emerald-400 to-teal-500', soft: 'bg-emerald-50 text-emerald-600' }].map((item) => <div key={item.label} className="group relative overflow-hidden rounded-2xl border border-slate-100 bg-white p-5 shadow-sm transition duration-300 hover:-translate-y-0.5 hover:shadow-lg"><div className={`absolute right-0 top-0 h-20 w-20 translate-x-5 -translate-y-5 rounded-full bg-gradient-to-br opacity-10 ${item.className}`} /><div className="relative flex items-start justify-between"><div><p className="text-xs font-medium text-slate-500">{item.label}</p><p className="mt-2 text-3xl font-bold tracking-tight text-slate-900">{loading ? '-' : item.value}</p><p className="mt-2 text-[11px] text-slate-400">{item.note}</p></div><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${item.soft}`}><item.icon className="h-5 w-5" /></span></div></div>)}</div>

    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.7fr)_minmax(320px,0.9fr)]">
      <div className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-start justify-between"><div><p className="text-xs font-semibold text-indigo-600">发布活跃度</p><h2 className="mt-1 text-base font-bold text-slate-900">近 7 天订单趋势</h2></div><span className="rounded-xl bg-indigo-50 px-3 py-1.5 text-xs font-semibold text-indigo-600">{metrics.total} 个订单</span></div><div className="h-60"><ResponsiveContainer width="100%" height="100%"><AreaChart data={publishTrend} margin={{ top: 10, right: 6, left: -24, bottom: 0 }}><defs><linearGradient id="orderTrend" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#6366f1" stopOpacity={0.35} /><stop offset="95%" stopColor="#6366f1" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#94a3b8' }} dy={8} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#94a3b8' }} /><Tooltip cursor={{ stroke: '#c7d2fe', strokeWidth: 1 }} contentStyle={{ borderRadius: 14, border: '1px solid #e2e8f0', boxShadow: '0 10px 25px rgba(15,23,42,.08)', fontSize: 12 }} formatter={(value: number) => [`${value} 个`, '新建订单']} /><Area type="monotone" dataKey="orders" stroke="#6366f1" strokeWidth={3} fill="url(#orderTrend)" /></AreaChart></ResponsiveContainer></div></div>
      <div className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-fuchsia-600">订单进度</p><h2 className="mt-1 text-base font-bold text-slate-900">状态分布</h2></div><LayoutDashboard className="h-5 w-5 text-fuchsia-400" /></div><div className="relative mx-auto mt-3 h-44 max-w-[230px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={statusData.length ? statusData : [{ name: '暂无订单', value: 1 }]} dataKey="value" nameKey="name" innerRadius={48} outerRadius={70} paddingAngle={4} stroke="none">{(statusData.length ? statusData : [{ name: '暂无订单', value: 1 }]).map((item, index) => <Cell key={item.name} fill={statusData.length ? chartColors[index] : '#e2e8f0'} />)}</Pie><Tooltip contentStyle={{ borderRadius: 14, border: '1px solid #e2e8f0', fontSize: 12 }} formatter={(value: number) => [`${value} 个`, '订单']} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-2xl font-bold text-slate-900">{loading ? '-' : metrics.total}</span><span className="text-[10px] text-slate-400">全部订单</span></div></div><div className="grid grid-cols-2 gap-2">{statusData.length ? statusData.map((item, index) => <div key={item.name} className="flex items-center gap-2 rounded-xl bg-slate-50 px-2.5 py-2 text-[11px]"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: chartColors[index] }} /><span className="min-w-0 flex-1 truncate text-slate-500">{item.name}</span><span className="font-semibold text-slate-700">{item.value}</span></div>) : <p className="col-span-2 py-2 text-center text-xs text-slate-400">暂无订单数据</p>}</div></div>
    </div>

    <div className="grid gap-6 lg:grid-cols-[minmax(0,1.25fr)_minmax(340px,0.75fr)]"><div className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm sm:p-6"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-semibold text-orange-600">优先处理</p><h2 className="mt-1 text-base font-bold text-slate-900">待办中心</h2></div><Link href="/advertiser/orders" className="flex items-center gap-1 text-xs font-semibold text-indigo-600 hover:text-indigo-700">查看订单 <ArrowRight className="h-3.5 w-3.5" /></Link></div><div className="grid gap-3 sm:grid-cols-3">{todoItems.map((item) => <Link key={item.label} href={item.href} className="group overflow-hidden rounded-2xl border border-slate-100 bg-white transition hover:-translate-y-0.5 hover:shadow-md"><div className={`h-1.5 bg-gradient-to-r ${item.className}`} /><div className="p-4"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${item.ring}`}><item.icon className="h-4 w-4" /></span><p className="mt-4 text-xs text-slate-500">{item.label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{loading ? '-' : item.value}</p><p className="mt-3 flex items-center text-[11px] font-medium text-slate-400 group-hover:text-indigo-600">立即处理 <ArrowRight className="ml-1 h-3 w-3" /></p></div></Link>)}</div></div><div className="role-primary-gradient overflow-hidden rounded-3xl p-5 text-white shadow-sm sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-white/80">预算概览</p><h2 className="mt-1 text-base font-bold">订单预算分布</h2></div><WalletCards className="h-5 w-5 text-white/80" /></div><p className="mt-5 text-3xl font-bold">{loading ? '-' : formatMoney(metrics.totalBudget)}</p><p className="mt-1 text-xs text-white/65">累计发布订单预算</p><div className="mt-5 h-28"><ResponsiveContainer width="100%" height="100%"><BarChart data={categoryBudget} layout="vertical" margin={{ top: 0, right: 8, left: 0, bottom: 0 }}><XAxis type="number" hide /><YAxis type="category" dataKey="name" width={64} tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: 'rgba(255,255,255,.75)' }} /><Tooltip cursor={{ fill: 'rgba(255,255,255,.12)' }} contentStyle={{ borderRadius: 12, border: '1px solid rgba(255,255,255,.25)', background: 'var(--role-primary-dark)', color: '#fff', fontSize: 11 }} formatter={(value: number) => [formatMoney(value), '预算']} /><Bar dataKey="budget" radius={[0, 7, 7, 0]} fill="#ffffff" fillOpacity={0.88} /></BarChart></ResponsiveContainer></div>{!categoryBudget.length && <p className="-mt-12 text-center text-xs text-white/65">发布订单后将展示类目预算</p>}</div></div>

    <div className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold text-sky-600">最近动态</p><h2 className="mt-1 text-base font-bold text-slate-900">订单进展</h2></div><div className="flex items-center gap-3"><span className="rounded-xl bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">{activeRules} 条审核流启用中</span><Link href="/advertiser/orders" className="flex items-center gap-1 text-xs font-semibold text-indigo-600 hover:text-indigo-700">全部订单 <ArrowRight className="h-3.5 w-3.5" /></Link></div></div>{loading && <div className="py-10 text-center text-sm text-slate-400">加载中…</div>}{!loading && !recentOrders.length && <div className="rounded-2xl bg-slate-50 py-12 text-center"><FolderKanban className="mx-auto h-7 w-7 text-slate-300" /><p className="mt-3 text-sm font-medium text-slate-500">还没有发布订单</p><OrderModeDropdownButton label="现在创建第一份需求" className="mt-2 inline-flex items-center text-xs font-semibold text-indigo-600" /></div>}{!loading && recentOrders.length > 0 && <div className="grid gap-3 lg:grid-cols-5">{recentOrders.map((order) => { const status = statusMap[orderStatus(order)] || { label: order.status, className: 'bg-slate-100 text-slate-600' }; return <Link key={order.id} href="/advertiser/orders" className="group rounded-2xl border border-slate-100 bg-slate-50/60 p-4 transition hover:-translate-y-0.5 hover:border-indigo-100 hover:bg-white hover:shadow-md"><div className="flex items-start justify-between gap-2"><Badge className={`border-0 px-2 py-0.5 text-[10px] ${status.className}`}>{status.label}</Badge><ArrowRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-indigo-500" /></div><p className="mt-5 line-clamp-2 min-h-10 text-sm font-semibold leading-5 text-slate-800">{order.title}</p><div className="mt-4 flex items-center justify-between border-t border-slate-200/70 pt-3 text-[11px] text-slate-400"><span>{formatDate(order.updatedAt || order.createdAt)}</span><span className="font-semibold text-slate-700">{formatMoney(Number(order.budget || 0))}</span></div></Link>; })}</div>}</div>
  </section>;
}
